modLoader="javafml" 
loaderVersion="[41,)" 
license="MIT"
[[mods]] 
modId="stockmarketmod" 
version="${file.jarVersion}" 
displayName="Stock Market Mod" 
logoFile="examplemod.png" 
credits="Stock Market Mod by teggo" 
authors="teggo" 
description='''
Stock Market Mod by teggo
'''
[[dependencies.stockmarketmod]] 
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.stockmarketmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
